name: Linux Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'

      - run: flutter pub get
      - run: flutter build linux --release

      - name: Release Bundle Archive
        uses: actions/upload-artifact@v2
        with:
          name: Release Bundle Archive
          path: build/linux/release/bundle/feedity

